@baseUrl = http://localhost:3333
@authToken = {{authenticate_admin.response.body.$.access_token}}

# @name create_admin
POST {{baseUrl}}/accounts/admin
Content-Type: application/json

{
  "name": "John Doe",
  "cpf": "999.999.999-99",
  "password": "123456"
}

###

# @name authenticate_admin
POST {{baseUrl}}/sessions/admin
Content-Type: application/json

{
  "cpf": "999.999.999-99",
  "password": "123456"
}

###

# @name create_order
POST {{baseUrl}}/orders
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "customerId": "customerId",
  "description": "Package 01"
}
